scheme_version: 1
token: token             # Replace with a desired token
os:
  hostname: node1        # Set a hostname. This can be omitted if DHCP server offers hostnames.
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHi2nERpA7LgenPrQARllH1+p0L2BIIQbaoRhUtXB7Q6nax+VI5Fcwz2w36Vv+OaWPJmfo0F8D9CnE9YriSd2pm5GDCMX+F7N2EuTl2PnL+c6zydvmvP+P3gKwteILhc2eoqnwvrdY+65nPtkg1YconvkTIZGsiljj7Z05j34Uk6szup908QU6CeEIsvSvaJpNlo272EvSEBJdZ3722X1OQMBSdxu82GO8Lhs2hxzQVKrQKq1eAexNVp5/w8YnV4GO51NWGPdI0S43zcsAb/0LegcrdaKRAP5kYnJeETBadw3hPS9WCyUEZzHJnzamcOWE11mGFylWfxne60hDqRtAMuODJYAH2MziOch7IcOvg3ShBuUQT8HcZMKwEiORJeLASJjc0GIYv+0rTCPPLAPWOiIepKoqrnkEVZpdmuCBLqyU3EB3mq7TGJn9MTuVP2cc1WJxUmkSB973noeZvnYaT7wG9sP3V7QKenCY15NKLixEg9ne1+xdU6I3lHPSYWgvjJdqvgCjGriksDcISKcWbnE87QZXPmmaU62FZQaFxbpDUUmcGeuIyiW8/a1wfUlC5D4w7elk7fnRdvFP+zeqMLPMDi4ea0PIMVjgIcmjTE2MioXjRLtEpju0xTG2S2fn7SlQTn9jy8DoPGBamAWTj2cn54+J5uWEA6JvDXK+0Q==# Replace with your public key
  password: p@ssword     # Replace with a your password
  ntp_servers:
  - 0.suse.pool.ntp.org
  - 1.suse.pool.ntp.org
install:
  mode: create
  management_interface:
    interfaces:
    - name: ens5
    default_route: true
    method: dhcp
    bond_options:
      mode: balance-tlb
      miimon: 100
  device: /dev/sda       # The target disk to install
  iso_url: https://releases.rancher.com/harvester/master/harvester-master-amd64.iso
#  tty: ttyS1,115200n8   # For machines without a VGA console

  vip: 10.10.0.19
  vip_mode: dhcp                   # Or static
  vip_hw_addr: 52:54:00:ec:0e:0b   # Leave empty when vip_mode is static
